### ISSUE TITLE
Debug / Build Events

### ISSUE THREAD

**Issue by truevis** [jeremytammik/StringSearch#1]
To get this to work in Revit 2015:
Change Start external program to C:\Program Files\Autodesk\Revit 2015\Revit.exe

Edit your Post-build command line to this:
copy "$(ProjectDir)ADNPlugin-StringSearch.addin" "$(AppData)\Autodesk\REVIT\Addins\2015"
copy "$(ProjectDir)bin\debug\ADNPlugin-StringSearch.dll" "$(AppData)\Autodesk\REVIT\Addins\2015"

**Comment by jeremytammik** [comment]
hi eric, thank you, done, and updated project.
